% This code was generated by Google Gemini on November 12th, 2025.
% log_sine_sweep.m - Generates a logarithmic sine sweep (exponential chirp)
% for use in acoustic measurements and system identification.

% --- 1. Define Sweep Parameters ---

% Start Frequency (Hz)
f1 = 1;
% End Frequency (Hz). Typically half the sampling rate (Nyquist frequency).
f2 = 22050;
% Sweep Duration (seconds)
T = 10;
% Sampling Rate (samples per second) - A common audio standard.
Fs = 44100;

% --- 2. Generate Time Vector ---

% Total number of samples
N = Fs * T;
% Time vector from 0 to T with N points
t = linspace(0, T, N);

% --- 3. Calculate Logarithmic Phase Function ---

% The instantaneous frequency f(t) for a logarithmic sweep is:
% f(t) = f1 * (f2/f1)^(t/T)
% The phase phi(t) is the integral of 2*pi*f(t) dt.

% Constant K is used to simplify the phase calculation:
K = T / log(f2 / f1);

% Phase function phi(t) for a logarithmic sweep (in radians):
% The .* and ./ operators perform element-wise operations on vectors.
phi = 2 * pi * f1 * K * ( (f2/f1).^(t./T) - 1 );

% --- 4. Generate Signal ---

% The sine sweep signal s(t) is sin(phi(t))
s = sin(phi);

% --- 5. Normalization and Saving ---

% Normalize the signal to prevent clipping and ensure full scale (-1 to 1)
s_norm = s / max(abs(s));

% Save the signal to a 16-bit PCM WAV file
filename = "log_sine_sweep_1_to_22050Hz_10s.wav";
audiowrite(filename, s_norm, Fs);
disp(['Generated and saved file: ', filename]);

% --- 6. Visualization (Plotting) ---

% Plot the beginning of the time domain signal
figure(1);
plot(t(1:round(Fs/50)), s_norm(1:round(Fs/50))); % Plot first 1/50th of a second
title('Time Domain Signal (First 20ms)');
xlabel('Time (s)');
ylabel('Amplitude (Normalized)');
grid on;

% Plot the frequency domain (Spectrum) to confirm the full bandwidth
% Calculate the Fast Fourier Transform (FFT)
S_fft = fft(s_norm);
% Get the magnitude spectrum and normalize to the number of samples
S_mag = abs(S_fft / N);
% Only display the single-sided spectrum (up to the Nyquist frequency)
f = Fs*(0:N/2)/N;
S_single_sided = S_mag(1:N/2+1);
S_single_sided(2:end-1) = 2*S_single_sided(2:end-1); % Correct DC and Nyquist components

figure(2);
semilogx(f, 20*log10(S_single_sided));
axis([f1 Fs/2 -100 0]); % Set X-axis from f1 to Fs/2, Y-axis from -100dB to 0dB
title('Frequency Spectrum (Magnitude in dB)');
xlabel('Frequency (Hz) [Log Scale]');
ylabel('Magnitude (dB)');
grid on;
set(gca, 'xscale', 'log'); % Ensure the X-axis is logarithmic for the spectrum